#!/bin/bash

PDB=${ORACLE_PDB}
PDB_UPPER=${PDB^^}
SID_UPPER=${ORACLE_SID^^}

sqlplus -s / as sysdba <<EOF
ALTER SESSION SET CONTAINER=${PDB_UPPER};

connect system/${ORACLE_PWD}@${PDB};

CREATE TABLESPACE ${IMART_TABLESPACE_NAME}
DATAFILE '/opt/oracle/oradata/${SID_UPPER}/${PDB_UPPER}/${IMART_TABLESPACE_NAME}.dbf' SIZE 7000M REUSE 
LOGGING
ONLINE
BLOCKSIZE 8K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

CREATE PROFILE ${IMART_PROFILE_NAME} LIMIT
SESSIONS_PER_USER UNLIMITED
CPU_PER_SESSION UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
PRIVATE_SGA UNLIMITED
COMPOSITE_LIMIT UNLIMITED
CPU_PER_CALL UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL;

CREATE USER ${IMART_USER_NAME}
IDENTIFIED BY "${IMART_USER_PASSWORD}"
DEFAULT TABLESPACE ${IMART_TABLESPACE_NAME}
TEMPORARY TABLESPACE TEMP
PROFILE ${IMART_PROFILE_NAME};

GRANT AUDIT_ADMIN TO ${IMART_USER_NAME};

GRANT CDB_DBA TO ${IMART_USER_NAME};

GRANT CONNECT TO ${IMART_USER_NAME};

GRANT DBA TO ${IMART_USER_NAME};

GRANT PDB_DBA TO ${IMART_USER_NAME};

GRANT RESOURCE TO ${IMART_USER_NAME};

GRANT ALTER ANY TYPE TO ${IMART_USER_NAME};

GRANT CREATE ANY TABLE TO ${IMART_USER_NAME};

GRANT CREATE ANY VIEW TO ${IMART_USER_NAME};

GRANT UNLIMITED TABLESPACE TO ${IMART_USER_NAME};
EOF
